lib: [
  "/home/onofre/PersonalProjects/studies/ocamlStudies/ImageProcessing2/_esy/default/store/b/imageprocessing2-189d4874/install/default/lib/imageproc/META"
  "/home/onofre/PersonalProjects/studies/ocamlStudies/ImageProcessing2/_esy/default/store/b/imageprocessing2-189d4874/install/default/lib/imageproc/dune-package"
  "/home/onofre/PersonalProjects/studies/ocamlStudies/ImageProcessing2/_esy/default/store/b/imageprocessing2-189d4874/install/default/lib/imageproc/opam"
]
bin: [
  "/home/onofre/PersonalProjects/studies/ocamlStudies/ImageProcessing2/_esy/default/store/b/imageprocessing2-189d4874/install/default/bin/imageproc.exe"
]
doc: [
  "/home/onofre/PersonalProjects/studies/ocamlStudies/ImageProcessing2/_esy/default/store/b/imageprocessing2-189d4874/install/default/doc/imageproc/LICENSE"
  "/home/onofre/PersonalProjects/studies/ocamlStudies/ImageProcessing2/_esy/default/store/b/imageprocessing2-189d4874/install/default/doc/imageproc/README.md"
]
